# overlays/prod/patch-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 2
  template:
    spec:
      containers:
      - name: app-nginx
        image: yrs8/app-nginx-prod:v1.5
        resources:
          requests:
            cpu: 20m  # 最小 CPU 使用量
          limits:
            cpu: 50m  # 最大 CPU 使用量
        env:
        - name: env
          value: "production"