services:
  app-nginx-service:
    build:
      context: ./nginx  # Dockerfile の場所
    image: app-nginx-${env_short}  # ビルドされたイメージの名前
    volumes:
      - ./nginx/default-local.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    environment:
      - env=${env}

  app-php-service:
    build:
      context: ./php  # Dockerfile の場所
      args:
        - ENV=${env}
    image: app-php-${env_short}  # ビルドされたイメージの名前
    volumes:
      - ./php:/var/www/html
    environment:
      - env=${env}