# deployment-dev.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-nginx
  template:
    metadata:
      labels:
        app: app-nginx
    spec:
      containers:
      - name: app-nginx
        image: yrs8/app-nginx-dev:v1.3
        imagePullPolicy: Always
        env:
        - name: env
          value: "development"

        # Pod が稼働しているかどうか確認
        livenessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 5  # コンテナ起動後、ヘルスチェックを開始するまでの遅延時間（秒）
          periodSeconds: 10       # ヘルスチェックの間隔（秒）
          timeoutSeconds: 5       # ヘルスチェックの応答タイムアウト時間（秒）

        # Pod がトラフィックを受け入れる準備ができているかどうか確認
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5  # コンテナ起動後、チェックを開始するまでの遅延時間（秒）
          periodSeconds: 10       # チェックの間隔（秒）
          timeoutSeconds: 5       # チェックの応答タイムアウト時間（秒）

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-php
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-php
  template:
    metadata:
      labels:
        app: app-php
    spec:
      containers:
      - name: app-php
        image: yrs8/app-php-dev:v1.2
        imagePullPolicy: Always
        env:
        - name: env
          value: "development"

        # Pod が稼働しているかどうか確認
        livenessProbe:
          initialDelaySeconds: 5  # コンテナ起動後、ヘルスチェックを開始するまでの遅延時間（秒）
          periodSeconds: 10       # ヘルスチェックの間隔（秒）
          tcpSocket:
            port: 9000            # PHP-FPM がリッスンしているポート

        # Pod がトラフィックを受け入れる準備ができているかどうか確認
        readinessProbe:
          initialDelaySeconds: 5  # コンテナ起動後、チェックを開始するまでの遅延時間（秒）
          periodSeconds: 10       # チェックの間隔（秒）
          tcpSocket:
            port: 9000            # PHP-FPM がリッスンしているポート

---
apiVersion: v1
kind: Service
metadata:
  name: app-nginx-service
spec:
  selector:
    app: app-nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer

---
apiVersion: v1
kind: Service
metadata:
  name: app-php-service
spec:
  selector:
    app: app-php
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 9000