# overlays/prod/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

patches:
- path: patch-deployment.yaml
  target:
    kind: Deployment
- path: patch-hpa.yaml
  target:
    kind: HorizontalPodAutoscaler
- path: patch-pdb.yaml
  target:
    kind: PodDisruptionBudget