# deployment-prod.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-nginx
spec:
  replicas: 2  # Pod のレプリカ数
  selector:
    matchLabels:
      app: app-nginx
  template:
    metadata:
      labels:
        app: app-nginx
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - app-nginx
            topologyKey: "kubernetes.io/hostname"
      containers:
      - name: app-nginx
        image: yrs8/app-nginx-prod:v1.4
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 20m  # 最小 CPU 使用量
          limits:
            cpu: 50m  # 最大 CPU 使用量
        env:
        - name: env
          value: "production"

        # Pod の生存確認設定
        livenessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 5  # コンテナ起動後、ヘルスチェックを開始するまでの遅延時間（秒）
          periodSeconds: 10       # ヘルスチェックの間隔（秒）
          timeoutSeconds: 5       # ヘルスチェックの応答タイムアウト時間（秒）

        # Pod の準備完了確認設定
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5  # コンテナ起動後、チェックを開始するまでの遅延時間（秒）
          periodSeconds: 10       # チェックの間隔（秒）
          timeoutSeconds: 5       # チェックの応答タイムアウト時間（秒）

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-php
spec:
  replicas: 2  # Pod のレプリカ数
  selector:
    matchLabels:
      app: app-php
  template:
    metadata:
      labels:
        app: app-php
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - app-php
            topologyKey: "kubernetes.io/hostname"
      containers:
      - name: app-php
        image: yrs8/app-php-prod:v1.3
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 20m    # 最小 CPU 使用量
          limits:
            cpu: 50m    # 最大 CPU 使用量
        env:
        - name: env
          value: "production"

        # Pod の生存確認設定
        livenessProbe:
          initialDelaySeconds: 5  # コンテナ起動後、ヘルスチェックを開始するまでの遅延時間（秒）
          periodSeconds: 10       # ヘルスチェックの間隔（秒）
          tcpSocket:
            port: 9000            # php-fpm がリッスンしているポート

        # Pod の準備完了確認設定
        readinessProbe:
          initialDelaySeconds: 5  # コンテナ起動後、チェックを開始するまでの遅延時間（秒）
          periodSeconds: 10       # チェックの間隔（秒）
          tcpSocket:
            port: 9000            # php-fpm がリッスンしているポート

---
apiVersion: v1
kind: Service
metadata:
  name: app-nginx-service
spec:
  selector:
    app: app-nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer

---
apiVersion: v1
kind: Service
metadata:
  name: app-php-service
spec:
  selector:
    app: app-php
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 9000

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: app-nginx-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: app-nginx
  minReplicas: 2  # スケールアウトの最小値
  maxReplicas: 5  # スケールアウトの最大値
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50  # CPU 使用率でスケールアウト

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: app-php-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: app-php
  minReplicas: 2  # スケールアウトの最小値
  maxReplicas: 10 # スケールアウトの最大値
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50  # CPU 使用率でスケールアウト

---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: app-nginx-pdb
spec:
  minAvailable: 1  #常に利用可能な Pod の最小数
  selector:
    matchLabels:
      app: app-nginx

---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: app-php-pdb
spec:
  minAvailable: 1  #常に利用可能な Pod の最小数
  selector:
    matchLabels:
      app: app-php