# application-prod.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: k8s-test
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/yrs8/k8s-test.git
    targetRevision: HEAD
    path: manifests/kustomize/overlays/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated: {}