# overlays/dev/patch-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: app-nginx
        image: yrs8/app-nginx-dev:v1.4
        resources:
          requests:
            cpu: 20m  # 最小 CPU 使用量
          limits:
            cpu: 50m  # 最大 CPU 使用量
        env:
        - name: env
          value: "development"