# overlays/dev/patch-configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  default.conf: |
    # 共通設定をマージ
    {{- .Files.Get "../../../../base/nginx/configmap.yaml" | indent 4 }}
    server {
        server_name k8s-test.dev;
    }