# base/php/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-php
spec:
  selector:
    matchLabels:
      app: app-php
  template:
    metadata:
      labels:
        app: app-php
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:  # 推奨要件
          - weight: 1
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - app-php
              topologyKey: "kubernetes.io/hostname"  # Pod を分散配置
      containers:
      - name: app-php
        imagePullPolicy: Always
        env:
        - name: env
          value: "production"

        # Pod の生存確認設定
        livenessProbe:
          initialDelaySeconds: 5  # コンテナ起動後、ヘルスチェックを開始するまでの遅延時間（秒）
          periodSeconds: 10       # ヘルスチェックの間隔（秒）
          tcpSocket:
            port: 9000            # php-fpm がリッスンしているポート

        # Pod の準備完了確認設定
        readinessProbe:
          initialDelaySeconds: 5  # コンテナ起動後、チェックを開始するまでの遅延時間（秒）
          periodSeconds: 10       # チェックの間隔（秒）
          tcpSocket:
            port: 9000            # php-fpm がリッスンしているポート