# base/nginx/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-nginx
spec:
  selector:
    matchLabels:
      app: app-nginx
  template:
    metadata:
      labels:
        app: app-nginx
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:  # 推奨要件
          - weight: 1
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - app-nginx
              topologyKey: "kubernetes.io/hostname"  # Pod を分散配置
      containers:
      - name: app-nginx
        imagePullPolicy: Always

        # Pod の生存確認設定
        livenessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 5  # コンテナ起動後、ヘルスチェックを開始するまでの遅延時間（秒）
          periodSeconds: 10       # ヘルスチェックの間隔（秒）
          timeoutSeconds: 5       # ヘルスチェックの応答タイムアウト時間（秒）

        # Pod の準備完了確認設定
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5  # コンテナ起動後、チェックを開始するまでの遅延時間（秒）
          periodSeconds: 10       # チェックの間隔（秒）
          timeoutSeconds: 5       # チェックの応答タイムアウト時間（秒）

        # マウントした ConfigMap の設定ファイルを読み込む
        volumeMounts:
        - name: config-volume
          mountPath: /etc/nginx/conf.d

      volumes:
      - name: config-volume
        configMap:
          name: nginx-config