# overlays/prod/patch-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-deployment
spec:
  replicas: 2
  template:
    spec:
      containers:
      - name: app-php
        image: yrs8/app-php-prod:v1.4
        resources:
          requests:
            cpu: 20m  # 最小 CPU 使用量
          limits:
            cpu: 50m  # 最大 CPU 使用量
        env:
        - name: env
          value: "production"